"""Setup helpers for loading external board and deck definitions."""

from game_setup.loaders import (
    build_board_package_from_dicts,
    build_board_package_from_files,
    build_catalog_registry,
    build_game_definition_from_dicts,
    build_game_definition_from_files,
    create_game_state_from_files,
    default_catalog_registry,
    load_card_catalog,
    resolve_catalog,
    save_board_package_to_files,
)
from game_setup.market_setup import (
    ABERRATIONS_DECK_ID,
    SPECIAL_RECRUIT_IDS,
    DeckProfile,
    MarketSetup,
    combine_two_deck_market_setup,
    compute_special_stacks,
    discover_full_deck_profiles,
    is_aberrations_in_market,
    pick_pair_for_target,
    pick_random_pair,
)
from game_setup.random_state_search import (
    find_state,
    find_state_and_save,
    generate_states,
    has_card_in_hand,
    has_card_in_market,
    has_enemy_troop_at_site,
)
from game_setup.scenario_generation.card_scenarios import (
    FORCED_INJECTIONS_FILENAME,
    CardScenarioGenerator,
    ensure_card_scenario,
    find_card_scenario,
    generate_card_scenarios,
    iter_roster_card_ids,
    write_forced_injection_notes,
)
from game_setup.scenarios import (
    CatalogVersionMismatchError,
    Scenario,
    ScenarioMetadata,
    load_game_state_from_scenario,
    load_scenario,
    save_game_state,
    save_scenario,
)

__all__ = [
    "ABERRATIONS_DECK_ID",
    "CardScenarioGenerator",
    "CatalogVersionMismatchError",
    "DeckProfile",
    "FORCED_INJECTIONS_FILENAME",
    "MarketSetup",
    "SPECIAL_RECRUIT_IDS",
    "Scenario",
    "ScenarioMetadata",
    "build_board_package_from_dicts",
    "build_board_package_from_files",
    "build_catalog_registry",
    "build_game_definition_from_dicts",
    "build_game_definition_from_files",
    "combine_two_deck_market_setup",
    "compute_special_stacks",
    "create_game_state_from_files",
    "default_catalog_registry",
    "discover_full_deck_profiles",
    "ensure_card_scenario",
    "find_card_scenario",
    "find_state",
    "find_state_and_save",
    "generate_card_scenarios",
    "generate_states",
    "has_card_in_hand",
    "has_card_in_market",
    "has_enemy_troop_at_site",
    "is_aberrations_in_market",
    "iter_roster_card_ids",
    "load_card_catalog",
    "load_game_state_from_scenario",
    "load_scenario",
    "pick_pair_for_target",
    "pick_random_pair",
    "resolve_catalog",
    "save_board_package_to_files",
    "save_game_state",
    "save_scenario",
    "write_forced_injection_notes",
]