"""Protocol defining the session interface used by the game viewer.

``engine_c.bindings.session.CSession`` satisfies this protocol; the viewer is
C-engine only.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class SessionLike(Protocol):
    @property
    def state(self) -> object: ...
    @property
    def move_count(self) -> int: ...
    def is_terminal(self) -> bool: ...
    def legal_moves(self) -> list: ...
    def submit_move(self, move) -> object | None: ...
    def save(self, path: str) -> None: ...
    @classmethod
    def load(cls, path: str, **kwargs) -> SessionLike: ...
